export const connectorForm = [
  {
    title: 'Add Connector',
    form: [
      {
        type: 'select',
        name: 'type',
        value: ['connector4'],
        label: 'Type',
        placeholder: 'Select Type',
        options: [{ value: 'Connectors', label: 'Connectors' }],
        required: true,
        validation: {
          name: 'type',
          required: true,
          errorMessage: 'Type is required',
          min: 0,
          max: 0,
        },
      },
      {
        type: 'text',
        value: [''],
        label: 'Name',
        name: 'connectorName',
        placeholder: 'Enter Name',
        options: [],
        required: true,
        validation: {
          name: 'connectorName',
          required: true,
          errorMessage: 'Connector name is required',
          min: 0,
          max: 0,
        },
      },
    ],
  },
  {
    title: ' Properties',
    form: [
      {
        type: 'text',
        value: [''],
        name: 'endPoint',
        label: 'End Point',
        placeholder: 'Enter End Point',
        options: [],
        required: true,
        validation: {
          name: 'endPoint',
          required: true,
          errorMessage: 'Endpoint is required',
          min: 0,
          max: 0,
        },
      },
      {
        type: 'text',
        value: [''],
        label: 'User Name',
        name: 'userName',
        placeholder: 'Enter User Name',
        options: [],
        required: true,
        validation: {
          name: 'userName',
          required: true,
          errorMessage: 'User Name is required',
          min: 0,
          max: 0,
        },
      },
      {
        type: 'password',
        value: [''],
        label: 'Password',
        name: 'password',
        placeholder: 'Enter Password',
        options: [],
        required: true,
        validation: {
          name: 'password',
          required: true,
          errorMessage: 'Password is required',
          min: 0,
          max: 0,
        },
      },
      {
        type: 'text',
        value: [''],
        label: 'Port',
        name: 'port',
        placeholder: 'Enter Port',
        options: [],
        required: true,
        validation: {
          name: 'port',
          required: true,
          errorMessage: 'Port is required',
          min: 0,
          max: 0,
        },
      },
    ],
  },
];

export default connectorForm;
